# ignore_for_file: sort_pub_dependencies

name: surf_places
description: "Final assignment from the Surf Flutter Summer School"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  places_api:
    path: packages/places_api

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  go_router: ^16.0.0
  surf_lint_rules: ^4.0.0
  flutter_bloc: ^9.1.1
  talker_flutter: ^4.9.3
  talker_dio_logger: ^4.9.3
  talker_bloc_logger: ^4.9.3
  get_it: ^8.1.0
  flutter_svg: ^2.2.0
  flutter_dotenv: ^5.2.1
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  screenshot: ^3.0.0
  share_plus: ^11.0.0
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  go_router_builder: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - fonts/
    - assets/icons/wrapper/
    - assets/icons/search/
    - assets/icons/place/
    - assets/icons/common/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
